Repository team2-software-developers/Pathfinder, pull requests merged in 2021-07, with the labels that each got.

#12 #11 updated project name in package.json
  package.json
Labels: bug

#14 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#16 #15 added React Components
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/About.jsx
  client/src/components/Home.jsx
  client/src/components/Navbar.css
  client/src/components/Navbar.jsx
  client/src/components/Phenomenon.jsx
  client/src/index.js
  package-lock.json
Labels: feature

#30 Devops/heroku
  package-lock.json
  package.json
  src/server.js
Labels: enhancement

#25 Feature/23
  client/package.json
  src/routes/about.route.js
  src/routes/date.route.js
  src/routes/phenomenon.route.js
  src/server.js
Labels: bug, feature

#34 #33 removed comments in package.json
  client/package.json
Labels: bug

#38 #37 removed axios from back end
  package-lock.json
  package.json
Labels: bug

#40 #27 create controller for phenomenon
  src/controller/phenomenon.controller.js
  src/routes/phenomenon.route.js
Labels: feature

#44 Styling modifications on the About and Phenomenon pages
  client/src/App.js
  client/src/assets/bg.png
  client/src/assets/bg2.png
  client/src/assets/dyatalov/01d.jpeg
  client/src/assets/dyatalov/02d.jpeg
  client/src/assets/dyatalov/03d.jpeg
  client/src/assets/dyatalov/folder_item01.png
  client/src/assets/ranch/01r.jpg
  client/src/assets/ranch/02r.jpg
  client/src/assets/ranch/folder_item02.png
  client/src/assets/spaceman/01s.jpg
  client/src/assets/spaceman/folder_item03.png
  client/src/assets/taured/01t.jpg
  client/src/assets/taured/02t.jpg
  client/src/assets/taured/folder_item04.png
  client/src/components/About.css
  client/src/components/About.jsx
  client/src/components/Folders.css
  client/src/components/Folders.jsx
  client/src/components/Navbar.css
  client/src/components/Phenomenon.css
  client/src/components/Phenomenon.jsx
Labels: help wanted
